#!/bin/bash

## DOOR3 Docksal package, v1.0
##
## Run theme compilation using webpack
##
## Usage: fin tb <command>

THEME_PATH_INSIDE_CONTAINER="/var/www/${DOCROOT}/themes/custom/${THEME_NAME}"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
MAIN_THEME_PATH="${DOCROOT_PATH}/themes/custom/${THEME_NAME}"

install_packages() {
  fin exec "cd ${THEME_PATH_INSIDE_CONTAINER}; yarn install"
  set +e
}

echo "Running build the theme ${THEME_PATH_INSIDE_CONTAINER}"

echo "${MAIN_THEME_PATH}/yarn.lock"

if [ -f "${MAIN_THEME_PATH}/yarn.lock" ]; then
    echo "yarn.lock is available, just running theme build..."
else
    echo "yarn.lock is not available, deleting node_modules and npm install\n"
    rm -rf $THEME_PATH_INSIDE_CONTAINER/node_modules
    install_packages
fi

fin exec "cd ${THEME_PATH_INSIDE_CONTAINER}; npm run $1"
